
CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username TEXT NOT NULL,
    password TEXT not null,
    role_id INTEGER
        REFERENCES roles(id) ON DELETE CASCADE NOT NULL, 
    company_id INTEGER
        REFERENCES companies(id) ON DELETE CASCADE NOT NULL
);
